config/routes.rb
Rails.application.routes.draw do

  resources :blogs, except: [:index] do
    resources :posts, only: [:new, :create]
  end
  resources :posts, only: [:show, :edit, :update, :destroy]
  resources :comments, only: [:create, :destroy]
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    member do
      get :deactivate
    end
  end

  namespace :me do
    match 'stories/public', to: 'stories#public', as: :public_stories, via: :get
    match 'stories/drafts', to: 'stories#drafts', as: :drafts_stories, via: :get
    match 'blogs', to: 'blogs#index', as: :blogs, via: :get
  end

  authenticated :user do
    root to: 'home#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#front'
  end

  match :top, to: 'home#top', as: :top, via: :get

  match :search, to: 'search#index', as: :search, via: :get

  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post

  match :bookmark, to: 'bookmarks#create', as: :bookmark, via: :post
  match :unbookmark, to: 'bookmarks#destroy', as: :unbookmark, via: :post
  match :bookmarks, to: 'bookmarks#index', as: :bookmarks, via: :get

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable

  acts_as_voter
  acts_as_follower

  has_many :blogs, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  mount_uploader :avatar, AvatarUploader

  validates_presence_of :name

  def self.search(query)
    if query
      where("LOWER(name) LIKE ?", "%#{query.downcase}%")
    else
      all()
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_user
  before_action :check_ownership, only: [:edit, :update]

  def show
    @posts = @user.posts.where(is_draft: false)
                .paginate(page: params[:page], per_page: 10)
                .order(cached_scoped_like_votes_up: :desc)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def deactivate
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :about, :avatar)
    end

    def check_ownership
      redirect_to current_user unless @user == current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def is_current_user?(user)
    user == current_user
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit class: "btn" %>
  </div>
<% end %>

app/views/users/_info.html.erb
<div id="user-<%= user.id %>" class="user-info">
  <div class="info">
      <%= render 'shared/avatar', resource: user %>
      <h4><%= link_to user.name, user %></h4>
  </div>
  <div class="content">
    <p><%= truncate(user.about, length: 200) %></p>
  </div>
</div>

app/views/users/deactivate.html.erb
<div class="row">
<div class="col-md-10 col-md-offset-1">
  <div class="post-box deactivate">
    <h3>Deactivate</h3>
    <hr>
    <h5>Unhappy with Bloggy? Hit the Button below to cancel account.</h5>
    <br>
    <%= button_to 'Cancel my account', registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete, class: "btn" %>
</div>
</div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="post-box blog-edit">
      <h4>Edit Profile</h4>
      <hr>
      <%= form_for @user do |f| %>
        <h3>
          <div class="field">
            <%= f.text_field :name, placeholder: "Name" %>
          </div>
        </h3>

        <div class="field">
          <%= f.text_area :about, placeholder: "About" %>
        </div>

        <div class="form-group">
          <%= render 'shared/avatar', resource: @user %>
          <%= f.file_field :avatar %>
        </div>

        <div class="actions">
          <%= submit_tag 'Update', class: "btn" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div id="user-<%= @user.id %>" class="blog-show post-box">

      <% if is_current_user?(@user) %>
        <div class="actions pull-right">
          <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= fa_icon 'angle-down' %>
            </button>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit Profile', edit_user_path(@user) %></li>
              <li><%= link_to 'Change password', edit_user_registration_path %></li>
              <li><%= link_to 'Deactivate', deactivate_user_path(@user) %></li>
            </ul>
          </div>
        </div>
      <% end %>

      <%= render 'shared/avatar', resource: @user %>

      <h2><%= @user.name %></h3>
      <h4><%= @user.about %></h5>

    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
      <div id="posts">
        <%= render(@posts) %>
      </div>
      <%= render 'shared/paginate', resources: @posts %>
  </div>
</div>

app/views/users/show.js.erb
$('#posts').append("<%= j render(@posts) %>");
<%= render 'shared/paginate', resources: @posts %>