config/routes.rb
Rails.application.routes.draw do

  resources :blogs, except: [:index] do
    resources :posts, only: [:new, :create]
  end
  resources :posts, only: [:show, :edit, :update, :destroy]
  resources :comments, only: [:create, :destroy]
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    member do
      get :deactivate
    end
  end

  namespace :me do
    match 'stories/public', to: 'stories#public', as: :public_stories, via: :get
    match 'stories/drafts', to: 'stories#drafts', as: :drafts_stories, via: :get
    match 'blogs', to: 'blogs#index', as: :blogs, via: :get
  end

  authenticated :user do
    root to: 'home#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#front'
  end

  match :top, to: 'home#top', as: :top, via: :get

  match :search, to: 'search#index', as: :search, via: :get

  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post

  match :bookmark, to: 'bookmarks#create', as: :bookmark, via: :post
  match :unbookmark, to: 'bookmarks#destroy', as: :unbookmark, via: :post
  match :bookmarks, to: 'bookmarks#index', as: :bookmarks, via: :get

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post

end

app/views/shared/_actions.html.erb
<div class="row">
  <% if resource.class.name == 'Comment' %>
    <div class="col-md-2 like pull-right">
      <%= render 'likes/form', likeable: resource %>
    </div>
  <% else %>
    <div class="col-md-2 like pull-left">
      <%= render 'likes/form', likeable: resource %>
    </div>
  <% end %>
  <% if resource.class.name == 'Post' %>
    <div class="col-md-3 col-md-offset-5  comments-count">
        <span class="pull-right"><%= pluralize(resource.comments_count, 'comment') %></span>
    </div>
    <div class="col-md-2 bookmark pull-right">
        <%= render 'bookmarks/form', bookmarkable: resource %>
    </div>
  <% end %>
</div>

app/views/shared/_avatar.html.erb
<%= image_tag resource.avatar.url || 'avatar.svg', class: 'img-circle' %>

app/views/shared/_cover.html.erb
<% if resource.cover.url %>
  <div class="cover" style="background-image: url(<%= resource.cover.url %>);"></div>
<% else %>
  <div class="cover" style="background-image: url(/assets/cover.png);"></div>
<% end %>

app/views/shared/_created_at.html.erb
<%= time_ago_in_words(activity.created_at) %> ago

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Bloggy!', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path, class: 'active' %></li>
        <li><%= link_to 'Top stories', top_path %></li>
        <li><%= link_to 'Bookmarks', bookmarks_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= form_tag search_path, :method => 'get', class: "navbar-form navbar-left", role: "search" do %>
            <div class="form-group search-form">
              <%= text_field_tag :query, params[:query], class: 'form-control', placeholder: 'Search'  %>
            </div>
          <% end %>
        </li>
      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Write a story</a>
          <ul class="dropdown-menu">
          <% current_user.blogs.each do |blog| %>
            <li><%= link_to blog.name, new_blog_post_path(blog) %></li>
          <% end %>
            <li>
              <%= link_to '+ Create a new blog', new_blog_path %>
            </li>
          </ul>
        </li>
        <li class="dropdown">

          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Blogs', me_blogs_path %></li>
            <li><%= link_to 'Drafts and stories', me_drafts_stories_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Profile', current_user %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to 'Write a story', user_session_path %></li>
        <li><%= link_to 'Sign in / Sign up', user_session_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_paginate.html.erb
<div id="endless-scroll" class="text-center hidden">
  <%= image_tag 'ajax-loader.gif' %>
  <%= will_paginate resources %>
</div>

app/views/shared/_paginate.js.erb
<% if resources.next_page %>
  $(".pagination").replaceWith("<%= j will_paginate(resources) %>");
  $(".pagination").hide();
<% else %>
  $(window).off('scroll');
  $("#endless-scroll").remove();
<% end %>