config/routes.rb
Rails.application.routes.draw do

  resources :blogs, except: [:index] do
    resources :posts, only: [:new, :create]
  end
  resources :posts, only: [:show, :edit, :update, :destroy]
  resources :comments, only: [:create, :destroy]
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    member do
      get :deactivate
    end
  end

  namespace :me do
    match 'stories/public', to: 'stories#public', as: :public_stories, via: :get
    match 'stories/drafts', to: 'stories#drafts', as: :drafts_stories, via: :get
    match 'blogs', to: 'blogs#index', as: :blogs, via: :get
  end

  authenticated :user do
    root to: 'home#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#front'
  end

  match :top, to: 'home#top', as: :top, via: :get

  match :search, to: 'search#index', as: :search, via: :get

  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post

  match :bookmark, to: 'bookmarks#create', as: :bookmark, via: :post
  match :unbookmark, to: 'bookmarks#destroy', as: :unbookmark, via: :post
  match :bookmarks, to: 'bookmarks#index', as: :bookmarks, via: :get

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  include PublicActivity::Common

  def block!
    self.update_attribute(:blocked, true)
  end

  validates_presence_of :follower
  validates_presence_of :followable
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_followable
  respond_to :js

  def create
    current_user.follow @followable
  end

  def destroy
    current_user.stop_following @followable
  end

  private
    def find_followable
      @followable_type = params[:followable_type].classify
      @followable = @followable_type.constantize.find(params[:followable_id])
    end
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_form.html.erb
<div id="<%= followable.class.to_s.downcase %>-<%= followable.id %>-follow" class="follow-form">
  <% if user_signed_in? %>
      <% if current_user.following? followable %>
        <%= form_tag unfollow_path(followable_type: followable.class.to_s, followable_id: followable.id), method: :post, remote: true do %>
          <% button_tag class: "btn" do %>
            unfollow
          <% end %>
        <% end %>
      <% else %>
        <%= form_tag follow_path(followable_type: followable.class.to_s, followable_id: followable.id), remote: true do %>
          <% button_tag class: "btn" do %>
            follow
          <% end %>
        <% end %>
      <% end %>
  <% end %>
</div>

app/views/follows/create.js.erb
$("#<%= @followable.class.to_s.downcase %>-<%= @followable.id %>-follow").replaceWith("<%=j render('follows/form', followable: @followable) %>");

app/views/follows/destroy.js.erb
$("#<%= @followable.class.to_s.downcase %>-<%= @followable.id %>-follow").replaceWith("<%=j render('follows/form', followable: @followable) %>");