config/routes.rb
Rails.application.routes.draw do

  resources :blogs, except: [:index] do
    resources :posts, only: [:new, :create]
  end
  resources :posts, only: [:show, :edit, :update, :destroy]
  resources :comments, only: [:create, :destroy]
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    member do
      get :deactivate
    end
  end

  namespace :me do
    match 'stories/public', to: 'stories#public', as: :public_stories, via: :get
    match 'stories/drafts', to: 'stories#drafts', as: :drafts_stories, via: :get
    match 'blogs', to: 'blogs#index', as: :blogs, via: :get
  end

  authenticated :user do
    root to: 'home#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#front'
  end

  match :top, to: 'home#top', as: :top, via: :get

  match :search, to: 'search#index', as: :search, via: :get

  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post

  match :bookmark, to: 'bookmarks#create', as: :bookmark, via: :post
  match :unbookmark, to: 'bookmarks#destroy', as: :unbookmark, via: :post
  match :bookmarks, to: 'bookmarks#index', as: :bookmarks, via: :get

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post

end

app/controllers/me/blogs_controller.rb
class Me::BlogsController < AuthOnlyController
  def index
    @user_blogs = current_user.blogs
    @following_blogs = current_user.following_by_type('Blog')
    @suggested_blogs = Blog.where.not(id: @following_blogs)
  end
end

app/controllers/me/stories_controller.rb
class Me::StoriesController < AuthOnlyController
  respond_to :html, :js

  def public
    @stories = current_user.posts.where(is_draft: false)
                  .paginate(page: params[:page], per_page: 10)
                  .order('created_at DESC')
  end

  def drafts
    @stories = current_user.posts.where(is_draft: true)
                  .paginate(page: params[:page], per_page: 10)
                  .order('created_at DESC')
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/me/stories/_draft.html.erb
<!-- <h3><%= link_to draft.title, draft %></h3>
<p>Last edited <%= time_ago_in_words(draft.updated_at) %> ago</p>
<ul>
  <li><%= link_to 'Edit', edit_post_path(draft) %></li>
  <li><%= link_to 'Delete', draft, method: :delete, data: { confirm: 'Are you sure?' } %></li>
</ul> -->

  <div class="content">
    <div class="pull-right">
      <span>
        <%= link_to 'Edit', edit_post_path(draft) %> |
        <%= link_to 'Delete', draft, method: :delete, data: { confirm: 'Are you sure?' } %>
      </span>
    </div>
    <h4><%= link_to draft.title, draft %></h4>
    <p>Last edited <%= time_ago_in_words(draft.updated_at) %> ago</p>
  </div>

app/views/me/stories/_public.html.erb
<div class="content">
  <div class="pull-right">
    <span>
      <%= link_to 'Edit', edit_post_path(public) %> |
      <%= link_to 'Delete', public, method: :delete, data: { confirm: 'Are you sure?' } %>
    </span>
  </div>
  <h4><%= link_to public.title, public %></h4>
  <p>Published on <%= public.updated_at.strftime("%b %d") %></p>
</div>

app/views/me/stories/drafts.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="post-box me-stories">
      <h1>Your stories</h1>
      <hr>
      <p><%= link_to 'Drafts', me_drafts_stories_path %> | <%= link_to 'Public', me_public_stories_path %> </p>
      <br>

      <% unless @stories.empty? %>
        <div id='stories'>
          <%= render(partial: 'me/stories/draft', collection: @stories) %>
        </div>
      <% else %>
        <div>
          <p>You have no drafts.</p>
        </div>
      <% end %>

      <%= render 'shared/paginate', resources: @stories %>
    </div>
  </div>
</div>

app/views/me/stories/drafts.js.erb
$('#stories').append("<%= j render(partial: 'me/stories/draft', collection: @stories) %>");
<%= render 'shared/paginate', resources: @stories %>

app/views/me/stories/public.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="post-box me-stories">
      <h1>Your stories</h1>
      <hr>
      <p><%= link_to 'Drafts', me_drafts_stories_path %> | <%= link_to 'Public', me_public_stories_path %></p>
      <br>

      <% unless @stories.empty? %>
        <div id='stories'>
          <%= render(partial: 'me/stories/public', collection: @stories) %>
        </div>
      <% else %>
        <div>
          <p>You haven’t published any public stories yet.</p>
        </div>
      <% end %>

      <%= render 'shared/paginate', resources: @stories %>
      </div>
    </div>
  </div>

app/views/me/stories/public.js.erb
$('#stories').append("<%= j render(partial: 'me/stories/public', collection: @stories) %>");
<%= render 'shared/paginate', resources: @stories %>